# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-15 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170824_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
    ]
