# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-15 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diposit',
            new_name='Deposit',
        ),
    ]
