# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-05-15 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20190515_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='user',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
